[package]
name = "tailwind_cli"
version = "3.4.1-0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duct = "0.13.7"
include-cargo-toml = "0.1.0"
tempfile = "3.9.0"
